export { default as About } from './About'
export { default as Experience } from './Experience'
export { default as Education } from './Education'
export { default as Skills } from './Skills'
export { default as Interests } from './Interests'
export { default as Awards } from './Awards'